Main:
  enable-command: true
  enable-npcs: true
  offduty: true
  uuid-support: true
  language: en_us
Messages:
  welcome: Welcome to my little shop.
  farewell: Thank you for your continued patronage.
  denial: I'm afraid you are not a shop member. I am not authorized to do business with you.
  closed: I am sorry, I am closed for business at this time.
PlayerShops:
  npc-for-hire: true
  npc-commission: 10.0
  npc-rental-price: 100.0
  right-click-player-shop: true
  onduty-in-shop-only: true
  npc-in-shop-only: true
  max-npcs-per-player: 2
